version: '3.3'
services:
  debian:
    image: takeyamajp/debian-sshd
    container_name: debian
    environment:
      ROOT_PASSWORD: next-terminal
    restart: always
    ports:
      - "10022:22"
    networks:
      next-terminal:
        ipv4_address: 172.77.77.100
  centos:
    image: jdeathe/centos-ssh:2.6.1
    container_name: centos
    environment:
      SSH_USER_PASSWORD: next-terminal
      SSH_USER: next-terminal
      SSH_PASSWORD_AUTHENTICATION: "true"
    restart: always
    ports:
      - "10023:22"
    networks:
      next-terminal:
        ipv4_address: 172.77.77.101
  mysql:
    image: ghcr.io/ysicing/mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: next-terminal
      MYSQL_USER: next-terminal
      MYSQL_PASSWORD: next-terminal
      MYSQL_ROOT_PASSWORD: next-terminal
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    ports:
      - "3306:3306"
    restart: always
    networks:
      next-terminal:
        ipv4_address: 172.77.77.2

  guacd:
    image: ghcr.io/ysicing/guacd:1.3.0
    container_name: guacd
    ports:
      - "4822:4822"
    restart: always
    networks:
      next-terminal:
        ipv4_address: 172.77.77.3

#  next-terminal:
#    container_name: next-terminal
#    image: ghcr.io/ysicing/next-terminal:latest
#    environment:
#      DB: "mysql"
#      MYSQL_HOSTNAME: "mysql"
#      MYSQL_PORT: 3306
#      MYSQL_USERNAME: "next-terminal"
#      MYSQL_PASSWORD: "next-terminal"
#      MYSQL_DATABASE: "next-terminal"
#    ports:
#      - "8088:8088"
#    volumes:
#      - 'terminal_drive_data:/usr/local/next-terminal/drive'
#      - 'terminal_recording_data:/usr/local/next-terminal/recording'
#    depends_on:
#      - mysql
#      - guacd
#    networks:
#      next-terminal:
#        ipv4_address: 172.77.77.4
#    restart: always

networks:
  next-terminal:
    ipam:
      driver: default
      config:
        - subnet: 172.77.77.0/24

volumes:
  mysql_data:
    driver: local
  terminal_drive_data:
    driver: local
  terminal_recording_data:
    driver: local