mode:
  debug: true
  demo: true
terminal:
  guacd:
    host: 192.168.31.242
    port: 4822
core:
  encryptionkey: ""
  http: 0.0.0.0:8080
  login:
    oauth2:
      enable: false
      type: github
      id: ""
      secret: ""
    ladp: false
    trynum: 3
    exp: 86400 #1d

ldap:
  domain: ysicing
  ldap_url: "ldap://172.18.0.2:389"
  ldap_search_dn: "cn=ldapsearch,ou=special,dc=ysicing,dc=me"
  ldap_search_password: "***666***"
  ldap_base_dn: "ou=ldap,dc=ysicing,dc=me"
  ldap_uid: sAMAccountName
  ldap_scope: 3
  ldap_connection_timeout: 30

db:
  type: mysql
  dsn: next-terminal:nt12345x@tcp(192.168.30.4:3306)/next-terminal?charset=utf8mb4&parseTime=True&loc=Local
  metrics:
    name: nt
    enable: true