mode:
  debug: true
  demo: true
terminal:
  guacd:
    host: 192.168.31.242
    port: 4822
core:
  encryptionkey: ""
  http: 0.0.0.0:8080
  login:
    trynum: 3
    exp: 86400 #1d
db:
  type: mysql
  dsn: next-terminal:nt12345x@tcp(192.168.30.4:3306)/next-terminal?charset=utf8mb4&parseTime=True&loc=Local
  metrics:
    name: nt
    enable: true