
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-terminal
  labels:
    app: next-terminal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-terminal
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: next-terminal
    spec:
      containers:
      - name: next-terminal
        image: ghcr.io/ysicing/next-terminal
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /conf/nt.yml
            name: ntcfg
            readOnly: true
            subPath: nt.yml
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 125Mi
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: ntcfg
                path: nt.yml
            name: ntcfg
          name: ntcfg
---
apiVersion: v1
kind: Service
metadata:
  name: next-terminal
  labels:
    app: next-terminal
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app: next-terminal
  type: ClusterIP
  ports:
  - name: http-8080
    protocol: TCP
    port: 8080
    targetPort: 8080
