name: Docker NT image

on:
  push:
    branches:
      - "ysicing"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build Static
        run: |
          make static
      - name: Login GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCRIO }}
      - name: Build docker
        run: |
          make docker
